var hierarchy =
[
    [ "_IMAGEHLP_LINE64", "struct___i_m_a_g_e_h_l_p___l_i_n_e64.html", null ],
    [ "_IMAGEHLP_MODULE64", "struct___i_m_a_g_e_h_l_p___m_o_d_u_l_e64.html", null ],
    [ "_IMAGEHLP_SYMBOL64", "struct___i_m_a_g_e_h_l_p___s_y_m_b_o_l64.html", null ],
    [ "_KDHELP64", "struct___k_d_h_e_l_p64.html", null ],
    [ "_tagADDRESS64", "struct__tag_a_d_d_r_e_s_s64.html", null ],
    [ "_tagSTACKFRAME64", "struct__tag_s_t_a_c_k_f_r_a_m_e64.html", null ],
    [ "StackWalker::CallstackEntry", "struct_stack_walker_1_1_callstack_entry.html", null ],
    [ "SallyAPI::Media::CAmazonInfo", "class_sally_a_p_i_1_1_media_1_1_c_amazon_info.html", null ],
    [ "SallyAPI::System::CAutoLock", "class_sally_a_p_i_1_1_system_1_1_c_auto_lock.html", null ],
    [ "SallyAPI::Core::CBaseObject", "class_sally_a_p_i_1_1_core_1_1_c_base_object.html", [
      [ "SallyAPI::Core::CFont", "class_sally_a_p_i_1_1_core_1_1_c_font.html", null ],
      [ "SallyAPI::GUI::CGUIBaseObject", "class_sally_a_p_i_1_1_g_u_i_1_1_c_g_u_i_base_object.html", [
        [ "SallyAPI::GUI::CControl", "class_sally_a_p_i_1_1_g_u_i_1_1_c_control.html", [
          [ "SallyAPI::GUI::CBreadcrumb", "class_sally_a_p_i_1_1_g_u_i_1_1_c_breadcrumb.html", null ],
          [ "SallyAPI::GUI::CButton", "class_sally_a_p_i_1_1_g_u_i_1_1_c_button.html", [
            [ "SallyAPI::GUI::CButtonBarButton", "class_sally_a_p_i_1_1_g_u_i_1_1_c_button_bar_button.html", null ],
            [ "SallyAPI::GUI::CListViewButton", "class_sally_a_p_i_1_1_g_u_i_1_1_c_list_view_button.html", null ],
            [ "SallyAPI::GUI::CRoundButton", "class_sally_a_p_i_1_1_g_u_i_1_1_c_round_button.html", null ],
            [ "SallyAPI::GUI::CSideMenuButton", "class_sally_a_p_i_1_1_g_u_i_1_1_c_side_menu_button.html", null ],
            [ "SallyAPI::GUI::CTabcontrolButton", "class_sally_a_p_i_1_1_g_u_i_1_1_c_tabcontrol_button.html", null ]
          ] ],
          [ "SallyAPI::GUI::CCheckbox", "class_sally_a_p_i_1_1_g_u_i_1_1_c_checkbox.html", null ],
          [ "SallyAPI::GUI::CDropDown", "class_sally_a_p_i_1_1_g_u_i_1_1_c_drop_down.html", null ],
          [ "SallyAPI::GUI::CEdit", "class_sally_a_p_i_1_1_g_u_i_1_1_c_edit.html", null ],
          [ "SallyAPI::GUI::CForm", "class_sally_a_p_i_1_1_g_u_i_1_1_c_form.html", [
            [ "SallyAPI::GUI::C3DCircle", "class_sally_a_p_i_1_1_g_u_i_1_1_c3_d_circle.html", null ],
            [ "SallyAPI::GUI::CAppBase", "class_sally_a_p_i_1_1_g_u_i_1_1_c_app_base.html", [
              [ "SallyAPI::GUI::CApplicationWindow", "class_sally_a_p_i_1_1_g_u_i_1_1_c_application_window.html", [
                [ "SallyAPI::GUI::CGameWindow", "class_sally_a_p_i_1_1_g_u_i_1_1_c_game_window.html", null ]
              ] ],
              [ "SallyAPI::GUI::CConfigPanel", "class_sally_a_p_i_1_1_g_u_i_1_1_c_config_panel.html", null ],
              [ "SallyAPI::GUI::CPopUpWindow", "class_sally_a_p_i_1_1_g_u_i_1_1_c_pop_up_window.html", [
                [ "SallyAPI::GUI::CAboutDialog", "class_sally_a_p_i_1_1_g_u_i_1_1_c_about_dialog.html", null ],
                [ "SallyAPI::GUI::CContextMenuPopUp", "class_sally_a_p_i_1_1_g_u_i_1_1_c_context_menu_pop_up.html", null ],
                [ "SallyAPI::GUI::CDialog", "class_sally_a_p_i_1_1_g_u_i_1_1_c_dialog.html", [
                  [ "SallyAPI::GUI::CDialogBox", "class_sally_a_p_i_1_1_g_u_i_1_1_c_dialog_box.html", [
                    [ "SallyAPI::GUI::CInputBox", "class_sally_a_p_i_1_1_g_u_i_1_1_c_input_box.html", null ],
                    [ "SallyAPI::GUI::CMessageBox", "class_sally_a_p_i_1_1_g_u_i_1_1_c_message_box.html", null ],
                    [ "SallyAPI::GUI::COpenDialog", "class_sally_a_p_i_1_1_g_u_i_1_1_c_open_dialog.html", null ],
                    [ "SallyAPI::GUI::CQuestionBox", "class_sally_a_p_i_1_1_g_u_i_1_1_c_question_box.html", null ]
                  ] ]
                ] ]
              ] ],
              [ "SallyAPI::GUI::CWizardPanel", "class_sally_a_p_i_1_1_g_u_i_1_1_c_wizard_panel.html", null ]
            ] ],
            [ "SallyAPI::GUI::CBottonMenu", "class_sally_a_p_i_1_1_g_u_i_1_1_c_botton_menu.html", null ],
            [ "SallyAPI::GUI::CButtonBar", "class_sally_a_p_i_1_1_g_u_i_1_1_c_button_bar.html", null ],
            [ "SallyAPI::GUI::CContextMenu", "class_sally_a_p_i_1_1_g_u_i_1_1_c_context_menu.html", null ],
            [ "SallyAPI::GUI::CEditBox", "class_sally_a_p_i_1_1_g_u_i_1_1_c_edit_box.html", null ],
            [ "SallyAPI::GUI::CFileBrowser", "class_sally_a_p_i_1_1_g_u_i_1_1_c_file_browser.html", null ],
            [ "SallyAPI::GUI::CGroupBox", "class_sally_a_p_i_1_1_g_u_i_1_1_c_group_box.html", null ],
            [ "SallyAPI::GUI::CLabelBox", "class_sally_a_p_i_1_1_g_u_i_1_1_c_label_box.html", null ],
            [ "SallyAPI::GUI::CListView", "class_sally_a_p_i_1_1_g_u_i_1_1_c_list_view.html", null ],
            [ "SallyAPI::GUI::CListViewExt", "class_sally_a_p_i_1_1_g_u_i_1_1_c_list_view_ext.html", null ],
            [ "SallyAPI::GUI::CNotificationBox", "class_sally_a_p_i_1_1_g_u_i_1_1_c_notification_box.html", null ],
            [ "SallyAPI::GUI::CNumberSelector", "class_sally_a_p_i_1_1_g_u_i_1_1_c_number_selector.html", null ],
            [ "SallyAPI::GUI::CRating", "class_sally_a_p_i_1_1_g_u_i_1_1_c_rating.html", null ],
            [ "SallyAPI::GUI::CScreensaverControl", "class_sally_a_p_i_1_1_g_u_i_1_1_c_screensaver_control.html", null ],
            [ "SallyAPI::GUI::CScreensaverControlLabel", "class_sally_a_p_i_1_1_g_u_i_1_1_c_screensaver_control_label.html", null ],
            [ "SallyAPI::GUI::CScrollForm", "class_sally_a_p_i_1_1_g_u_i_1_1_c_scroll_form.html", null ],
            [ "SallyAPI::GUI::CScrollList", "class_sally_a_p_i_1_1_g_u_i_1_1_c_scroll_list.html", null ],
            [ "SallyAPI::GUI::CSideMenu", "class_sally_a_p_i_1_1_g_u_i_1_1_c_side_menu.html", null ],
            [ "SallyAPI::GUI::CTabcontrol", "class_sally_a_p_i_1_1_g_u_i_1_1_c_tabcontrol.html", null ],
            [ "SallyAPI::GUI::CTopMenu", "class_sally_a_p_i_1_1_g_u_i_1_1_c_top_menu.html", null ],
            [ "SallyAPI::GUI::CVolumeControl", "class_sally_a_p_i_1_1_g_u_i_1_1_c_volume_control.html", null ]
          ] ],
          [ "SallyAPI::GUI::CHorizontalSeperator", "class_sally_a_p_i_1_1_g_u_i_1_1_c_horizontal_seperator.html", null ],
          [ "SallyAPI::GUI::CImageBox", "class_sally_a_p_i_1_1_g_u_i_1_1_c_image_box.html", [
            [ "SallyAPI::GUI::CBox2DObject", "class_sally_a_p_i_1_1_g_u_i_1_1_c_box2_d_object.html", null ],
            [ "SallyAPI::GUI::CWorking", "class_sally_a_p_i_1_1_g_u_i_1_1_c_working.html", null ]
          ] ],
          [ "SallyAPI::GUI::CLabel", "class_sally_a_p_i_1_1_g_u_i_1_1_c_label.html", null ],
          [ "SallyAPI::GUI::CProcessbar", "class_sally_a_p_i_1_1_g_u_i_1_1_c_processbar.html", null ],
          [ "SallyAPI::GUI::CRadioButton", "class_sally_a_p_i_1_1_g_u_i_1_1_c_radio_button.html", null ],
          [ "SallyAPI::GUI::CScreensaverControlButton", "class_sally_a_p_i_1_1_g_u_i_1_1_c_screensaver_control_button.html", null ],
          [ "SallyAPI::GUI::CScrollbar", "class_sally_a_p_i_1_1_g_u_i_1_1_c_scrollbar.html", null ],
          [ "SallyAPI::GUI::CSlider", "class_sally_a_p_i_1_1_g_u_i_1_1_c_slider.html", null ],
          [ "SallyAPI::GUI::CVerticalSeperator", "class_sally_a_p_i_1_1_g_u_i_1_1_c_vertical_seperator.html", null ]
        ] ],
        [ "SallyAPI::GUI::CWindow", "class_sally_a_p_i_1_1_g_u_i_1_1_c_window.html", null ]
      ] ]
    ] ],
    [ "SallyAPI::Core::CCamera", "class_sally_a_p_i_1_1_core_1_1_c_camera.html", null ],
    [ "SallyAPI::Database::CColumn", "class_sally_a_p_i_1_1_database_1_1_c_column.html", null ],
    [ "SallyAPI::Config::CConfig", "class_sally_a_p_i_1_1_config_1_1_c_config.html", null ],
    [ "SallyAPI::Core::CCounter", "class_sally_a_p_i_1_1_core_1_1_c_counter.html", null ],
    [ "SallyAPI::System::CCritSection", "class_sally_a_p_i_1_1_system_1_1_c_crit_section.html", null ],
    [ "SallyAPI::Database::CDatabaseConnection", "class_sally_a_p_i_1_1_database_1_1_c_database_connection.html", null ],
    [ "SallyAPI::Database::CDatabaseMetaData", "class_sally_a_p_i_1_1_database_1_1_c_database_meta_data.html", null ],
    [ "SallyAPI::Database::CDatabaseObject", "class_sally_a_p_i_1_1_database_1_1_c_database_object.html", null ],
    [ "SallyAPI::GUI::CDropDownItem", "class_sally_a_p_i_1_1_g_u_i_1_1_c_drop_down_item.html", null ],
    [ "SallyAPI::Exception::CException", "class_sally_a_p_i_1_1_exception_1_1_c_exception.html", [
      [ "SallyAPI::Exception::CExceptionError", "class_sally_a_p_i_1_1_exception_1_1_c_exception_error.html", null ],
      [ "SallyAPI::Exception::CExceptionWarning", "class_sally_a_p_i_1_1_exception_1_1_c_exception_warning.html", null ]
    ] ],
    [ "SallyAPI::Facebook::CFacebookDB", "class_sally_a_p_i_1_1_facebook_1_1_c_facebook_d_b.html", null ],
    [ "SallyAPI::Facebook::CFacebookManager", "class_sally_a_p_i_1_1_facebook_1_1_c_facebook_manager.html", null ],
    [ "SallyAPI::File::CFileActionController", "class_sally_a_p_i_1_1_file_1_1_c_file_action_controller.html", null ],
    [ "SallyAPI::Core::CFontManager", "class_sally_a_p_i_1_1_core_1_1_c_font_manager.html", null ],
    [ "SallyAPI::Core::CGame", "class_sally_a_p_i_1_1_core_1_1_c_game.html", null ],
    [ "SallyAPI::Config::CKeyboardLayout", "class_sally_a_p_i_1_1_config_1_1_c_keyboard_layout.html", null ],
    [ "SallyAPI::Config::CLanguageManager", "class_sally_a_p_i_1_1_config_1_1_c_language_manager.html", null ],
    [ "SallyAPI::GUI::CListViewItem", "class_sally_a_p_i_1_1_g_u_i_1_1_c_list_view_item.html", null ],
    [ "SallyAPI::System::CLogger", "class_sally_a_p_i_1_1_system_1_1_c_logger.html", null ],
    [ "SallyAPI::Media::CMediaHelper", "class_sally_a_p_i_1_1_media_1_1_c_media_helper.html", null ],
    [ "SallyAPI::System::CNumberGenerator", "class_sally_a_p_i_1_1_system_1_1_c_number_generator.html", null ],
    [ "SallyAPI::System::COption", "class_sally_a_p_i_1_1_system_1_1_c_option.html", null ],
    [ "SallyAPI::Core::COptionManager", "class_sally_a_p_i_1_1_core_1_1_c_option_manager.html", null ],
    [ "SallyAPI::GUI::SendMessage::CParameterBase", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_base.html", [
      [ "SallyAPI::GUI::SendMessage::CParameterApplicationInfo", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_application_info.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterControl", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_control.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterHoldClick", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_hold_click.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterInputBox", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_input_box.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterInteger", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_integer.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterIntegerVector", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_integer_vector.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterKeyboardRequestWords", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_keyboard_request_words.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterKeyValue", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_key_value.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterListItem", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_list_item.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterListItemHoldClick", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_list_item_hold_click.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterMessageBox", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_message_box.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterNotificationInfo", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_notification_info.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterNotificationOSM", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_notification_o_s_m.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterNotificationText", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_notification_text.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterOpenDialog", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_open_dialog.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterPoint", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_point.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterQuestionBox", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_question_box.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterRect", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_rect.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterScrollList", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_scroll_list.html", null ],
      [ "SallyAPI::GUI::SendMessage::CParameterString", "class_sally_a_p_i_1_1_g_u_i_1_1_send_message_1_1_c_parameter_string.html", null ]
    ] ],
    [ "SallyAPI::GUI::CPicture", "class_sally_a_p_i_1_1_g_u_i_1_1_c_picture.html", null ],
    [ "SallyAPI::Network::CPing", "class_sally_a_p_i_1_1_network_1_1_c_ping.html", null ],
    [ "SallyAPI::Database::CResultSet", "class_sally_a_p_i_1_1_database_1_1_c_result_set.html", null ],
    [ "SallyAPI::Database::CResultSetMetaData", "class_sally_a_p_i_1_1_database_1_1_c_result_set_meta_data.html", null ],
    [ "SallyAPI::Scheduler::CScheduler", "class_sally_a_p_i_1_1_scheduler_1_1_c_scheduler.html", null ],
    [ "SallyAPI::Scheduler::CSchedulerManager", "class_sally_a_p_i_1_1_scheduler_1_1_c_scheduler_manager.html", null ],
    [ "SallyAPI::GUI::CScrollListItem", "class_sally_a_p_i_1_1_g_u_i_1_1_c_scroll_list_item.html", null ],
    [ "SallyAPI::Config::CSmartKeyboard", "class_sally_a_p_i_1_1_config_1_1_c_smart_keyboard.html", null ],
    [ "SallyAPI::System::CSmartThreadPoolManager", "class_sally_a_p_i_1_1_system_1_1_c_smart_thread_pool_manager.html", null ],
    [ "SallyAPI::Speech::CSpeech", "class_sally_a_p_i_1_1_speech_1_1_c_speech.html", null ],
    [ "SallyAPI::Speech::CSpeechOutputManager", "class_sally_a_p_i_1_1_speech_1_1_c_speech_output_manager.html", null ],
    [ "SallyAPI::Database::CSQLException", "class_sally_a_p_i_1_1_database_1_1_c_s_q_l_exception.html", null ],
    [ "SallyAPI::Database::CStatement", "class_sally_a_p_i_1_1_database_1_1_c_statement.html", null ],
    [ "SallyAPI::Facebook::CStatusMessage", "class_sally_a_p_i_1_1_facebook_1_1_c_status_message.html", null ],
    [ "SallyAPI::String::CStringCompareWithArray", "class_sally_a_p_i_1_1_string_1_1_c_string_compare_with_array.html", null ],
    [ "SallyAPI::GUI::CTabcontrolItem", "class_sally_a_p_i_1_1_g_u_i_1_1_c_tabcontrol_item.html", null ],
    [ "SallyAPI::Core::CTexture", "class_sally_a_p_i_1_1_core_1_1_c_texture.html", null ],
    [ "SallyAPI::Core::CTextureManager", "class_sally_a_p_i_1_1_core_1_1_c_texture_manager.html", null ],
    [ "SallyAPI::Config::CTheme", "class_sally_a_p_i_1_1_config_1_1_c_theme.html", null ],
    [ "SallyAPI::Config::CThemePluginImage", "class_sally_a_p_i_1_1_config_1_1_c_theme_plugin_image.html", null ],
    [ "SallyAPI::System::CThread", "class_sally_a_p_i_1_1_system_1_1_c_thread.html", [
      [ "SallyAPI::Config::CReloadThemeImage", "class_sally_a_p_i_1_1_config_1_1_c_reload_theme_image.html", null ],
      [ "SallyAPI::Facebook::CFacebookThread", "class_sally_a_p_i_1_1_facebook_1_1_c_facebook_thread.html", null ],
      [ "SallyAPI::GUI::CThreadStarter", "class_sally_a_p_i_1_1_g_u_i_1_1_c_thread_starter.html", null ],
      [ "SallyAPI::GUI::CTimer", "class_sally_a_p_i_1_1_g_u_i_1_1_c_timer.html", null ],
      [ "SallyAPI::Network::CHttpSendRequestThread", "class_sally_a_p_i_1_1_network_1_1_c_http_send_request_thread.html", null ],
      [ "SallyAPI::Sound::CPlaySound", "class_sally_a_p_i_1_1_sound_1_1_c_play_sound.html", null ],
      [ "SallyAPI::Speech::CSpeechThread", "class_sally_a_p_i_1_1_speech_1_1_c_speech_thread.html", null ],
      [ "SallyAPI::System::CSmartThreadPollManagerThread", "class_sally_a_p_i_1_1_system_1_1_c_smart_thread_poll_manager_thread.html", null ],
      [ "SallyAPI::System::CSmartThreadPool", "class_sally_a_p_i_1_1_system_1_1_c_smart_thread_pool.html", null ]
    ] ],
    [ "SallyAPI::Sound::Volume::CVolumeManager", "class_sally_a_p_i_1_1_sound_1_1_volume_1_1_c_volume_manager.html", null ],
    [ "SallyAPI::Sound::Volume::CVolumeNotification", "class_sally_a_p_i_1_1_sound_1_1_volume_1_1_c_volume_notification.html", null ],
    [ "SallyAPI::Exception::CWinAPIExceptionHandler", "class_sally_a_p_i_1_1_exception_1_1_c_win_a_p_i_exception_handler.html", null ],
    [ "SallyAPI::GUI::CWindowMessage", "class_sally_a_p_i_1_1_g_u_i_1_1_c_window_message.html", null ],
    [ "SallyAPI::Date::DateHelper", "class_sally_a_p_i_1_1_date_1_1_date_helper.html", null ],
    [ "DEVICE_INFO", "struct_d_e_v_i_c_e___i_n_f_o.html", null ],
    [ "DEVICE_LIST", "struct_d_e_v_i_c_e___l_i_s_t.html", null ],
    [ "ExceptionCodeDescr", "struct_exception_code_descr.html", null ],
    [ "SallyAPI::File::FileHelper", "class_sally_a_p_i_1_1_file_1_1_file_helper.html", null ],
    [ "SallyAPI::GUI::GUIHelper", "class_sally_a_p_i_1_1_g_u_i_1_1_g_u_i_helper.html", null ],
    [ "HTMLReplace", "struct_h_t_m_l_replace.html", null ],
    [ "StackWalkerInternal::IMAGEHLP_MODULE64_V2", "struct_stack_walker_internal_1_1_i_m_a_g_e_h_l_p___m_o_d_u_l_e64___v2.html", null ],
    [ "SallyAPI::Network::NetworkHelper", "class_sally_a_p_i_1_1_network_1_1_network_helper.html", null ],
    [ "SallyAPI::String::PathHelper", "class_sally_a_p_i_1_1_string_1_1_path_helper.html", null ],
    [ "SallyAPI::System::SallyHelper", "class_sally_a_p_i_1_1_system_1_1_sally_helper.html", null ],
    [ "StackWalker", "class_stack_walker.html", [
      [ "SallyAPI::Exception::CExceptionStackWalker", "class_sally_a_p_i_1_1_exception_1_1_c_exception_stack_walker.html", null ]
    ] ],
    [ "StackWalkerInternal", "class_stack_walker_internal.html", null ],
    [ "SallyAPI::String::StringHelper", "class_sally_a_p_i_1_1_string_1_1_string_helper.html", null ],
    [ "SallyAPI::System::SystemHelper", "class_sally_a_p_i_1_1_system_1_1_system_helper.html", null ],
    [ "SallyAPI::Network::tagICMPECHO", "struct_sally_a_p_i_1_1_network_1_1tag_i_c_m_p_e_c_h_o.html", null ],
    [ "SallyAPI::Network::tagIPINFO", "struct_sally_a_p_i_1_1_network_1_1tag_i_p_i_n_f_o.html", null ]
];